### PR TITLE
In the Result -> Person association, always look for the current person (subId 1)

### LINKED ISSUE #776: Competition competitors count wrong
This happens because the Result -> Person association doesn't account for the fact that multiple Persons can share a WCA ID.

For example, if you have Joe Bob with subId 1 and Joeseph Bob with subId 2, and Joe Bob competed at your competition, you don't want to count him as 2 people.

### PR DESCRIPTION
**Pull request by jfly**
This fixes #776, but in a slightly different way from what @jonatanklosko suggested:

> I think I have a clean solution for this. By the way I can imagine other bugs linked with this. Basically I'd try to change this: https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/models/competition.rb#L13 to `{ distinct.current }`. I don't have ability to check it out as I'm not at home, so it would be really nice if someone could try this and make a PR if this works =) I think it's worth solving fast to let Oliver post the report ASAP.

I opted to do this inside of Result, rather than Competition, because I think it would make sense for us to eventually make WCA IDs unique in the Persons table (and have a PastPersons table for old citizenships/names/genders), and this feels more in line with that hypothetical future: only one human being did this result in competition.

### CODE REVIEW

File: WcaOnRails/spec/models/competition_spec.rb [hunk 1]
```diff
@@ -578,4 +578,21 @@
       expect(competition.website).to eq "https://external.website.com"
     end
   end
+
+  context "competitors" do
+    let!(:competition) { FactoryGirl.build(:competition) }
+
+    it "works" do
+      r1 = FactoryGirl.create :result, competition: competition
+      r2 = FactoryGirl.create :result, competition: competition
```
Comment (jonatanklosko) [inline WcaOnRails/spec/models/competition_spec.rb]: You can do
```ruby
FactoryGirl.create_list :result, 2, competition: competition
```

File: WcaOnRails/spec/models/result_spec.rb [hunk 2]
```diff
@@ -54,4 +54,15 @@
       expect(result.to_s :best).to eq "3/3 ?:??:??"
     end
   end
+
+  describe "person association" do
+    it "always looks for subId 1" do
+      person1 = FactoryGirl.create :person_with_multiple_sub_ids
+      person2 = Person.where(wca_id: person1.wca_id, subId: 2).first
```
Comment (jonatanklosko) [inline WcaOnRails/spec/models/result_spec.rb]: If you use `find_by` instead of `where` then you don't have to call `first` =)

**Comment by jfly** [comment]
Thanks for the comments, @jonatanklosko! I've updated the PR accordingly.

**Comment by jonatanklosko** [comment]
LGTM =)
