### PR TITLE
Fix a hidden N+1 query

### LINKED ISSUE #899: RegistrationsController#edit_registrations is very slow
Here are screenshots from NewRelic. The data is from the last 3h and there were at most 70rpm (avg 30rpm), so it's not like our server was being hammered at any time.

screen shot 2016-09-16 at 11 34 46 am

screen shot 2016-09-16 at 11 35 10 am

`RegistrationsController#do_actions_for_selected` isn't much faster btw (average response times for the last 3h):
screen shot 2016-09-16 at 11 38 08 am

### PR DESCRIPTION
**Pull request by viroulep**
Fixes #899.

I think all the "useless" selects we've seen on the edit_registrations page were created by the `map(&:event_object)` from `Registration.events` [here](https://github.com/cubing/worldcubeassociation.org/blob/fb29c4dfc1410e79cb4b4e372c5364a66aea63c5/WcaOnRails/app/models/registration.rb#L37).

IIRC, `marked_for_destruction?` should be use if we want to edit the events for a given registration, which is not the case here as we just want to read them.
Which lead me to the question: what do we need `Registration.events` for, as any view editing them will use [`saved_and_unsaved_events`](https://github.com/cubing/worldcubeassociation.org/blob/fb29c4dfc1410e79cb4b4e372c5364a66aea63c5/WcaOnRails/app/models/registration.rb#L95)?
I just went ahead and deleted the overriding method, and the N+1 query detector immediately spotted that we were doing something wrong, so it was easy to fix them.

So before merging this I'd like a feedback from @jonatanklosko or @pingskills to be sure all pages modifying the `registration_events` table use `Registration.saved_and_unsaved_events` ;)

### CODE REVIEW

File: WcaOnRails/app/models/registration.rb [hunk 1]
```diff
@@ -33,10 +33,6 @@ def accepted?
     !pending?
   end
 
-  def events
-    registration_events.reject(&:marked_for_destruction?).map(&:event_object).sort_by(&:rank)
-  end
```
Comment (jonatanklosko) [inline WcaOnRails/app/models/registration.rb]: I thought we got rid of all `event_object` methods, but it looks like one left (we don't need it as it does the same as `event` since event bacame a real model). Feel free to remove this from the Event model.

Comment (viroulep) [inline WcaOnRails/app/models/registration.rb]: Great, I just did that :)

**Comment by viroulep** [comment]
From @jonatanklosko's description I feel like these changes are needed regardless of if we want to improve even further the performances, so I'll go ahead and merge this now so that impacted delegates and organizers can manage their competitions again asap.

I'm interested to see how the "fixed" edit page compares to @timhabermaas solution in #903 using a pre-computed matrix :)
(I'll give another shot at newrelic later !)
