### PR TITLE
Fix issue with event ids passed as a hash

### LINKED ISSUE #472: Facebook url encoding kills competition search
When sending a link in facebook chat, the encoded URI ends up creating a "something went wrong" page. Here is the URI before and after facebook re-encodes it:

```
https://www.worldcubeassociation.org/competitions?utf8=%E2%9C%93&event_ids%5B%5D=333&event_ids%5B%5D=333ft&region=all&years=current&search&display=List
https://www.worldcubeassociation.org/competitions?utf8=%E2%9C%93&event_ids%5B0%5D=333&event_ids%5B1%5D=333ft&region=all&years=current&search&display=List
```

### PR DESCRIPTION
**Pull request by jonatanklosko**
Fixes #472.

### CODE REVIEW

File: WcaOnRails/spec/controllers/competitions_controller_spec.rb [hunk 1]
```diff
@@ -32,6 +32,11 @@
           get :index, event_ids: ["777", "333fm", "333oh"]
           expect(assigns(:competitions)).to eq [competition4]
         end
+
+        it "works when event_ids are passed as hash instead of an array (facebook redirection)" do
```
Comment (jfly) [inline WcaOnRails/spec/controllers/competitions_controller_spec.rb]: Can you add a link back to https://github.com/cubing/worldcubeassociation.org/issues/472?

**Comment by jfly** [comment]
LGTM!
