### PR TITLE
Fixed the datepicker for when you click outside.

### LINKED ISSUE #396: Datetimepicker can't tabNext if the user clicked in whitespace to defocus
This causes `$.tabNext();` to be called while the body of the page is focused, which scrolls me to the very top of the page. 

before:

2016-02-21_21 30 03_662x703_kaladin

after:

2016-02-21_21 30 06_662x703_kaladin

@pedrosino, can you look into this?

### PR DESCRIPTION
**Pull request by pedrosino**
Fixes #396

### CODE REVIEW

File: WcaOnRails/app/assets/javascripts/application.js [hunk 1]
```diff
@@ -77,6 +77,14 @@ $(function() {
     }
   });
 
+  // We use dp.hide to capture clicking on a date. We then tab to the next
+  // form item, so the picker is just one click away, in case the user made
+  // a mistake or wants to select a different date. This also triggers the
+  // 'blur' event, used above to validate the date.
+  $datetimepicker.on('dp.hide', function() {
+    $('input:not(input[type=button], input[type=submit], input[type=reset]), select, textarea').eq(parseInt($('input:not(input[type=button], input[type=submit], input[type=reset]), select, textarea').index($(this)), 10) + 1).focus();
```
Comment (jfly) [inline WcaOnRails/app/assets/javascripts/application.js]: What about if you're the very last element? Shouldn't this wrap around?

Listing all the types of focusable elements seems gross and not going to work in general (see how complicated it is: https://github.com/marklagendijk/jquery.tabbable/blob/master/jquery.tabbable.js#L109-L135).

Can we instead make use fo the :focusable or :tabable selectors provided by the jquery.tabbable library, and write some code that looks liek this: https://github.com/marklagendijk/jquery.tabbable/blob/master/jquery.tabbable.js#L50-L62, but instead uses `$(this)` instead of `current = $(':focus');`?

Comment (pedrosino) [inline WcaOnRails/app/assets/javascripts/application.js]: I was using :focusable, but it would move to a button (at the edit competition view). It kinda breaks the flow of the tabbing, but I'm fine with moving there to make it less gross.

Comment (pedrosino) [inline WcaOnRails/app/assets/javascripts/application.js]: Like this:
```Javascript
var focusables = $(":focusable");   
var current = focusables.index(this),
next = focusables.eq(current+1).length ? focusables.eq(current+1) : focusables.eq(0);
next.focus();
```

There is a problem. With datetimepickers, it will not hide once you click the date. Or when you choose a time. It will never hide until you click outside :P Not sure what to do with that.

**Comment by jfly** [comment]
LGTM, :shipit:
