### PR TITLE
Change how new competitions are created - fixes #416

### LINKED ISSUE #416: Confusing error when creating new competition
I created a new competition for NortheasternSpring2016 at https://www.worldcubeassociation.org/competitions.  I forgot that you're supposed to put the name of the competition, not the competition ID, so I entered "NortheasternSpring2016" into the "name" field and hit "submit".

At the top of the page I got a very confusing error message:

The form contains 6 errors:
Id can't be blank
Id is invalid
Name is invalid
Name can't be blank
Name is invalid
Competition nickname is invalid

This is way too many errors for forgetting two spaces, and none of them really say what I did wrong.  Also, "Name is invalid" came up twice.

Below the "name" field is a better error message: "The full name of the competition including the year at the end (e.g., European Rubik's Cube Championship 2006). Be sure to capitalize."  But it's not in a big red box, so I didn't notice it for about a minute.

### PR DESCRIPTION
**Pull request by pingskills**
The new page and edit page now share a partial form. The id and cellName are only validated if the name passes validation or it's an update. This is so the error messages can be simplified. Competitions can now be cloned from the competition nav bar.

Let me know if you think this is the right direction to head in. I think it simplifies the code and the user process flow. The clone competition functionality has now moved from the model to the controller.

Here are some screenshots:
The new page for creating a competition:
create-comp-new-screen

The error message if you don't add a year to the name:
create-comp-error-messages

The navigation bar with the clone link:
create-comp-nav-bar

The new screen after the clone link is hit:
create-comp-clone

I'd love to hear your thoughts

### CODE REVIEW

**Comment by jonatanklosko** [comment]
Now it's not obvious that you can clone the competition so I'd see here an info alert on the new competition page informing about this.

File: WcaOnRails/app/assets/javascripts/competitions.js [hunk 1]
```diff
@@ -1,26 +1,4 @@
...
-    };
-    competitionChanged();
-
-    selectize.on("change", competitionChanged);
-    selectize.$control_input.on("input", competitionChanged);
-  }
-});
-
-onPage('competitions#edit, competitions#update', function() {
+onPage('competitions#edit, competitions#new', function() {
```
Comment (jonatanklosko) [inline WcaOnRails/app/assets/javascripts/competitions.js]: You have to specify all the *actions* that renders the new/edit pages:
`'competitions#new competitions#create competitions#edit competitions#admin_edit competitions#clone_competition'`

File: WcaOnRails/app/controllers/competitions_controller.rb [hunk 2]
```diff
@@ -239,16 +232,35 @@ def edit
...
+      @competition.organizers |= cloned_competition.organizers
+      @competition.delegates |= cloned_competition.delegates
+    end
+    if current_user.any_kind_of_delegate?
+      @competition.delegates |= [current_user]
+    end
+    @competition.showAtAll = false
+    @competition.isConfirmed = false
+    render :new
+  end
```
Comment (jonatanklosko) [inline WcaOnRails/app/controllers/competitions_controller.rb]: I'd like to have this logic inside the model to slim down the controller as much as we can (it's big enough). In the current situation, instead of using the `before_validation` callback as before, it would be better just to make a method. Something like:
```ruby
# Called for the competition which we want to clone data from
def get_clone
  # All the logic here
  # Return a *new* competition with the attributes assigned
end
```

Then in the controller something like this:
```ruby
cloned_competition = Competition.find(params[:id])
@competition = cloned_competition.get_clone
```

File: WcaOnRails/app/views/competitions/_nav.html.erb [hunk 3]
```diff
@@ -50,6 +50,13 @@
             ])
         } %>
       <% end %>
+      <% if current_user && current_user.can_create_competitions? %>
+        <% nav_items << {
+          text: t('.menu.clone'),
+          path: clone_competition_path(@competition),
+          fa_icon: "lock",
```
Comment (jonatanklosko) [inline WcaOnRails/app/views/competitions/_nav.html.erb]: There is a ['clone' icon](http://fontawesome.io/icon/clone/). I'm not making any suggestion, just check it out and use whatever you find cooler =)

File: WcaOnRails/app/views/competitions/new.html.erb [hunk 4]
```diff
@@ -1,14 +1,7 @@
 <% provide(:title, t('.create_competition')) %>
+<% provide(:include_gmaps, true) %>
```
Comment (jonatanklosko) [inline WcaOnRails/app/views/competitions/new.html.erb]: Does it work if we remove this line both from here and `edit.html` and move it to `_competition_form.html.erb` ?

File: WcaOnRails/app/controllers/competitions_controller.rb [hunk 5]
```diff
@@ -239,16 +232,35 @@ def edit
...
+
   def nearby_competitions
-    @competition = Competition.find(params[:id])
+    @competition = Competition.new
     @competition.assign_attributes(competition_params)
     @competition.valid? # We only unpack dates _just before_ validation, so we need to call validation here
```
Comment (jonatanklosko) [inline WcaOnRails/app/controllers/competitions_controller.rb]: I feel like it would be much more expressive to make `unpack_dates` public and call it here instead of this workaround (if there are no obstacles to do so).

File: WcaOnRails/app/controllers/competitions_controller.rb [hunk 6]
```diff
@@ -239,16 +232,35 @@ def edit
...
     @competition_admin_view = params.key?(:competition_admin_view) && current_user.can_admin_results?
     render partial: 'nearby_competitions'
   end
 
   def time_until_competition
-    @competition = Competition.find(params[:id])
+    @competition = Competition.new
     @competition.assign_attributes(competition_params)
     @competition.valid? # We only unpack dates _just before_ validation, so we need to call validation here
```
Comment (jonatanklosko) [inline WcaOnRails/app/controllers/competitions_controller.rb]: Same as above.

File: WcaOnRails/app/controllers/competitions_controller.rb (hunk 2 above)
Comment (jfly) [inline WcaOnRails/app/controllers/competitions_controller.rb]: I like this suggestion. Maybe to follow FactoryGirl semantics, we could call the method `build_clone`?

File: WcaOnRails/app/models/competition.rb [hunk 7]
```diff
@@ -331,7 +311,11 @@ def latitude_radians
   def events
     # See https://github.com/cubing/worldcubeassociation.org/issues/95 for
```
Comment (jfly) [inline WcaOnRails/app/models/competition.rb]: nit: I think it makes more sense for this comment to live next to the line of code `eventSpecs.split...`

File: WcaOnRails/app/controllers/competitions_controller.rb [hunk 8]
```diff
@@ -239,16 +232,35 @@ def edit
...
+      @competition.delegates |= [current_user]
+    end
+    @competition.showAtAll = false
+    @competition.isConfirmed = false
+    render :new
+  end
+
   def nearby_competitions
-    @competition = Competition.find(params[:id])
+    @competition = Competition.new
```
Comment (jfly) [inline WcaOnRails/app/controllers/competitions_controller.rb]: Good call.

File: WcaOnRails/spec/features/create_competition_spec.rb [hunk 9]
```diff
@@ -14,43 +14,29 @@
...
     expect(Competition.all.length).to eq 1
     new_competition = Competition.find("NewComp2015")
     expect(new_competition.name).to eq "New Comp 2015"
     expect(new_competition.delegates).to eq [delegate]
-    expect(new_competition.venue).to eq ""
   end
 
   it 'can clone competition' do
-    visit "/competitions/new"
+    visit clone_competition_path(competition_to_clone)
```
Comment (jfly) [inline WcaOnRails/spec/features/create_competition_spec.rb]: MAN THIS TEST IS SO NICE NOW

File: WcaOnRails/app/models/competition.rb [hunk 10]
```diff
@@ -21,12 +21,15 @@ class Competition < ActiveRecord::Base
   MAX_ID_LENGTH = 32
   MAX_NAME_LENGTH = 50
   validates :id, presence: true, uniqueness: true, length: { maximum: MAX_ID_LENGTH },
-                 format: { with: /\A[a-zA-Z0-9]+\Z/ }
+                 format: { with: /\A[a-zA-Z0-9]+\Z/ }, if: :name_valid_or_updating?
+  private def name_valid_or_updating?
+    self.persisted? ? true : name.length <= MAX_NAME_LENGTH && name =~ ENDS_WITH_YEAR_RE
```
Comment (jfly) [inline WcaOnRails/app/models/competition.rb]: I don't think the ternary is serving any purpose here. Can this be rewritten as follows?

```
self.persisted? || (name.length <= MAX_NAME_LENGTH && name =~ ENDS_WITH_YEAR_RE)
```

More importantly, what is going on here? Why do we need to look at `.persisted?` now?

**Comment by jfly** [comment]
This is some awesome cleanup, @pingskills! I'm very pleased with this new direction.

File: WcaOnRails/app/controllers/competitions_controller.rb (hunk 2 above)
Comment (jonatanklosko) [inline WcaOnRails/app/controllers/competitions_controller.rb]: Awesome!

File: WcaOnRails/app/models/competition.rb [hunk 11]
```diff
@@ -331,7 +311,11 @@ def latitude_radians
   def events
     # See https://github.com/cubing/worldcubeassociation.org/issues/95 for
     # what these equal signs are about.
-    eventSpecs.split.map { |e| Event.find_by_id(e.split("=")[0]) }.sort_by &:rank
+    if eventSpecs
+      eventSpecs.split.map { |e| Event.find_by_id(e.split("=")[0]) }.sort_by &:rank
+    else
+      []
+    end
```
Comment (jonatanklosko) [inline WcaOnRails/app/models/competition.rb]: `(eventSpecs || []).split.map ...`

File: WcaOnRails/app/controllers/competitions_controller.rb (hunk 2 above)
Comment (pingskills) [inline WcaOnRails/app/controllers/competitions_controller.rb]: OK. This makes sense but I think I need to keep the following in the controller since in the model it won't know about curent_user:

`    if current_user.any_kind_of_delegate?
      @clone.delegates |= [current_user]
    end`

File: WcaOnRails/app/views/competitions/new.html.erb (hunk 4 above)
Comment (pingskills) [inline WcaOnRails/app/views/competitions/new.html.erb]: It does work :)

File: WcaOnRails/app/controllers/competitions_controller.rb (hunk 5 above)
Comment (pingskills) [inline WcaOnRails/app/controllers/competitions_controller.rb]: At the moment as it's called for validation purposes it adds to errors. If changed this to only unpack the dates we'd need to do the validation somewhere else. I'm not sure what is best here?

File: WcaOnRails/app/models/competition.rb (hunk 10 above)
Comment (pingskills) [inline WcaOnRails/app/models/competition.rb]: I want to perform this validation all the time on the edit page. Because someone could update the name and the cellName on the validation page and at that point I want to display both errors to the user. It's only on the new page that I don't want to validate the id and cellName if the name itself isn't valid.

**Comment by pingskills** [comment]
Thanks for your feedback everyone. I've updated the code to try and reflect your suggestions. Let me know what you think.

**Comment by pingskills** [comment]
When smoke testing I went to create a new competition, filled in all the details and tried to Confirm the competition (rather than create then confirm) but I got an error with the following code:

`    if params[:commit] == "Confirm" && current_user.can_confirm_competition?(@competition)
      competition_params[:isConfirmed] = true
    end`

This tries to call 
`  def can_confirm_competition?(competition)
    # We don't let competition organizers confirm competitions.
    can_admin_results? || competition.delegates.include?(self)
  end`

but as the competition only has delegate_ids and not any delegates at this point the competition.delegates.include?(self) fails. Any suggestions on how to handle this? I could make the new page only have a Create button but not a Confirm button?

File: WcaOnRails/app/controllers/competitions_controller.rb (hunk 2 above)
Comment (jonatanklosko) [inline WcaOnRails/app/controllers/competitions_controller.rb]: It would be sufficient to move only this if statement to controller and keep the rest inside the model.

File: WcaOnRails/app/views/competitions/new.html.erb (hunk 4 above)
Comment (jonatanklosko) [inline WcaOnRails/app/views/competitions/new.html.erb]: Great =)

File: WcaOnRails/app/controllers/competitions_controller.rb (hunk 5 above)
Comment (jonatanklosko) [inline WcaOnRails/app/controllers/competitions_controller.rb]: Ok, that just wasn't obvious from the comment that we need to add errors too.

File: WcaOnRails/app/controllers/competitions_controller.rb (hunk 2 above)
Comment (jonatanklosko) [inline WcaOnRails/app/controllers/competitions_controller.rb]: Oh sorry I see that's what you've done already =)

File: WcaOnRails/app/views/competitions/new.html.erb [hunk 12]
```diff
@@ -2,13 +2,6 @@
...
-
-  <%= simple_form_for @competition, html: { class: 'form-horizontal new-competition' }  do |f| %>
-    <%= render 'shared/error_messages', object: f.object %>
-
-    <%= f.input :name, required: true, autofocus: true %>
-    <%= f.input :competition_id_to_clone, as: :competition_id, only_one: true %>
-
-    <button type="submit" id="create-competition" class="btn btn-success"></button>
-  <% end %>
+  <%= alert :info, 'To clone an existing competition visit the information page for that competition and click the "Clone" link in the menu.', note: true %>
```
Comment (jonatanklosko) [inline WcaOnRails/app/views/competitions/new.html.erb]: Nice, anyway I think it shouldn't appear when we are already cloning a competition. So probably it would be better to set this alert in `flash.now` in the *new* action.

Comment (jfly) [inline WcaOnRails/app/views/competitions/new.html.erb]: Or alternatively, you could check if the action is `new` here, rather than `create`.

File: WcaOnRails/app/models/competition.rb [hunk 13]
```diff
@@ -21,12 +21,15 @@ class Competition < ActiveRecord::Base
   MAX_ID_LENGTH = 32
   MAX_NAME_LENGTH = 50
   validates :id, presence: true, uniqueness: true, length: { maximum: MAX_ID_LENGTH },
-                 format: { with: /\A[a-zA-Z0-9]+\Z/ }
+                 format: { with: /\A[a-zA-Z0-9]+\Z/ }, if: :name_valid_or_updating?
+  private def name_valid_or_updating?
+    self.persisted? || name.length <= MAX_NAME_LENGTH && name =~ ENDS_WITH_YEAR_RE
```
Comment (jfly) [inline WcaOnRails/app/models/competition.rb]: So, I'm still confused. Based on the boolean logic, this looks more like `name_valid_or_creating?`, or even `creating_or_name_valid?`.

> I want to perform this validation all the time on the edit page. Because someone could update the name and the cellName on the validation page and at that point I want to display both errors to the user. It's only on the new page that I don't want to validate the id and cellName if the name itself isn't valid.

I see. I'm nervous that this validation would allow people to create new competitions with invalid `id`s and `cellName`s, though. You could achieve this by adding a form manually via javascript, or using curl.

For now, I think it would be okay to just always enforce these validations. Admittedly, it would be confusing to users to get validation errors on fields they don't even see, but I think we could eventually port our automatic `id` and `cellName` computation to javascript, and get rid of the yucky mess inside our model to conditionally compute them. I think this would clean up our code, and provide a much nicer UX.

**Comment by LinusFresz** [comment]
Hey, 
Awesome work! This looks much more pleasant to create a competition!
I am not totally sure if this is already fixed (because mostly I don't understand what happens here), so I will just leave a quick note.

While creating a new competition today I experienced some trouble in cloning a former competition. I created a new competition for the German Nationals 2016 (officially confirmed yet) and wanted to clone the German Nationals 2015 page, as it takes place at the same venue. I got the following error:

The form contains 1 error:
WCA delegate(s) are not all delegates

I know where this problem comes from, as Björn Korbanka, who was one of the delegates at this competition, is not a delegate anymore. He retired at the end of last year.

Here is my request: would it be possible to be able to clone this competitions with former delegates who are not delegates anymore? I feel like there could be some warning ('WCA delegate(s) are not all delegates’) and in the cloning process they simply get deleted from the delegate list for this competition, but not be able to clone this competitions is kind of annoying, as all other information are the ones needed.

Never mind this post if you already fixed that! :)

All the best,
Linus

File: WcaOnRails/app/models/competition.rb (hunk 13 above)
Comment (jfly) [inline WcaOnRails/app/models/competition.rb]: PLEASE FORGET EVERYTHING I JUST SAID, @jonatanklosko SET ME STRAIGHT.

This looks great to me.

File: WcaOnRails/app/controllers/competitions_controller.rb [hunk 14]
```diff
@@ -29,6 +29,9 @@ class CompetitionsController < ApplicationController
 
   def new
     @competition = Competition.new
+    if current_user.any_kind_of_delegate?
+      @competition.delegates |= [current_user]
```
Comment (larspetrus) [inline WcaOnRails/app/controllers/competitions_controller.rb]: Is this meant to be `||=` ?

Comment (jonatanklosko) [inline WcaOnRails/app/controllers/competitions_controller.rb]: Came up with the same thought but it shouldn't. When using `||=` we expect that `@competition.delegates` is nil, whereas it's `#<ActiveRecord::Associations::CollectionProxy []>`. So we need to get the union here.

Comment (larspetrus) [inline WcaOnRails/app/controllers/competitions_controller.rb]: Aha! Don't think I've ever encountered `Array.|` before!

I'm used to seeing `@competition.delegates << current_user` to do this.

Comment (jfly) [inline WcaOnRails/app/controllers/competitions_controller.rb]: I agree, in this particular case, `<<` seems better.

Comment (jonatanklosko) [inline WcaOnRails/app/controllers/competitions_controller.rb]: Agree, with this someone may stumble upon this and have a temptation to change it (as me and Lars =) ).

Comment (pingskills) [inline WcaOnRails/app/controllers/competitions_controller.rb]: If I clone a competition that I am already a delegate for and use << then I'll end up with my user id twice in the delegate_ids, but it seems that simple_form handles this so maybe it's not an issue?

Comment (jfly) [inline WcaOnRails/app/controllers/competitions_controller.rb]: Are you sure that happens? I would have expected the fact that we're using ActiveRecord to prevent such a thing.

In this particular case, we just created a competition, so there are no delegates. Perhaps it would be cleanest to do:

```ruby
@competition.delegates = [current_user]
```

instead?

Comment (pingskills) [inline WcaOnRails/app/controllers/competitions_controller.rb]: Hi @jfly, I think you're right ActiveRecord must take care of this. If I clone a competition I'm already a delegate for I get the following values in delegate_ids, `value="6180,6181,6183,6180"` where I'm user 6180. But when I save the competition only the 3 unique records get stored in the database. So there are no real problems using << 

I think as this is cloning a competition we'd want to also clone the existing delegates rather than just set it to the current user.

**Comment by pingskills** [comment]
Does anyone have a suggestion on how to deal with the following code called when confirming a comp? 

`current_user.can_confirm_competition?(@competition)`

I have the confirm button on the new page, and this method checks competition.delegates which doesn't exist for a new competition? We only have the delegate_ids in the parameters.

I could take the confirm button off the new page, meaning a user would need to first create, and then they could confirm but it seems like an unnecessary step. I'd rather change the can_confirm_competition to check if @competition.delegates is nil and then check the delegate_ids passed in the parameters.

File: WcaOnRails/app/controllers/competitions_controller.rb (hunk 14 above)
Comment (pingskills) [inline WcaOnRails/app/controllers/competitions_controller.rb]: Actually although it saves the correct records to the database one of the test fails because of the duplicate record. I might leave it as |=

Here's the test that fails:

`      it 'clones a competition that they delegated' do
        # First, make ourselves the delegate of the competition we're going to clone.
        competition.delegates = [delegate]
        get :clone_competition, id: competition
        new_comp = assigns(:competition)
        expect(new_comp.id).to eq ""

        # Cloning a competition should clone its organizers.
        expect(new_comp.organizers.sort_by(&:id)).to eq []
        # When a delegate clones a competition, it should clone its organizers, and add
        # the delegate doing the cloning.
        expect(new_comp.delegates.sort_by(&:id)).to eq [delegate]
      end`

It's because the delegate is there twice.

**Comment by pingskills** [comment]
I modified the controller where it checks if a user can confirm a competition to first see if we have a @competition, otherwise check the delegate_ids in the params.

File: WcaOnRails/app/controllers/competitions_controller.rb [hunk 15]
```diff
@@ -359,8 +361,15 @@ def my_competitions
...
     end
-    if params[:commit] == "Confirm" && current_user.can_confirm_competition?(@competition)
-      competition_params[:isConfirmed] = true
+    # Ensure that the user is a delegate if they are confirming the competition.
+    if params[:commit] == "Confirm"
+      if @competition
+        if current_user.can_confirm_competition?(@competition)
+          competition_params[:isConfirmed] = true
+        end
+      elsif competition_params[:delegate_ids].split(",").include? current_user.id.to_s
```
Comment (pingskills) [inline WcaOnRails/app/controllers/competitions_controller.rb]: If we confirm a competition from the new page there is no @competition at this point in the code so in that case I'm checking that the user is in the delegate_ids to ensure they can confirm this competition.

Comment (jfly) [inline WcaOnRails/app/controllers/competitions_controller.rb]: Yikes. I'd rather remove the ability to confirm a competition from the New page. No delegate in their right mind is going to fill out that entire form without wanting to hit save a few times before confirming.

File: WcaOnRails/app/controllers/competitions_controller.rb (hunk 14 above)
Comment (larspetrus) [inline WcaOnRails/app/controllers/competitions_controller.rb]: I tried looking into this stuff, and it's fairly contentious and confusing. It seems Rails does this right with direct associations, if you specify :uniq on the relation, but not on `through` relations, and that's (debatably) a bug.

Or something... This feels like a bottomless hole so I stopped digging.

https://github.com/rails/rails/issues/8573

File: WcaOnRails/app/models/competition.rb [hunk 16]
```diff
@@ -96,25 +99,17 @@ def info
...
+    # Don't clone the following attributes.
+    attributes_to_clone = attributes
+    %w(id name cellName year month day endMonth endDay registration_open registration_close results_posted_at).each { |attribute| attributes_to_clone.delete attribute }
+    clone = Competition.new
+    clone.assign_attributes(attributes_to_clone)
+    clone.organizers = organizers
+    clone.delegates = delegates
+    clone.showAtAll = false
+    clone.isConfirmed = false
+    clone
```
Comment (jonatanklosko) [inline WcaOnRails/app/models/competition.rb]: I feel like cleaning this up. What about:
```ruby
NOT_CLONED_ATTRIBUTES = %w(id name cellName year month day endMonth endDay registration_open registration_close results_posted_at)
Competition.new(attributes.except(*NOT_CLONED_ATTRIBUTES)).tap do |clone|
  clone.assign_attributes showAtAll: false, isConfirmed: false
  clone.organizers = organizers
  clone.delegates = delegates
end
```

Comment (larspetrus) [inline WcaOnRails/app/models/competition.rb]: Yes, that really needs cleaning up!

I'd be a bit more ambitious and define both clonable and unclonable attributes. That makes this test possible...

`expect(Competition.column_names()).to match_array(Competition::CLONABLE_ATTRS + Competition::UNCLONABLE_ATTRS)`

..., which makes the clone code self maintaining! In the sense that if a column is added or renamed, the test will go Red, and we have to explicitly declare how the new column is treated.


Also, `showAtAll` and `isConfirmed` are set to `false` by the schema, so it seems wrong to set it here too.

Comment (jonatanklosko) [inline WcaOnRails/app/models/competition.rb]: Really nice idea with this explicit division!
Also that's a good note, it would be sufficient to add `showAtAll` and `isConfirmed` to unclonable attributes rather than this assigning =)

File: WcaOnRails/app/controllers/competitions_controller.rb (hunk 15 above)
Comment (pingskills) [inline WcaOnRails/app/controllers/competitions_controller.rb]: That will certainly make it simpler. I'll revert this and remove the confirm button in this situation.

File: WcaOnRails/app/controllers/competitions_controller.rb [hunk 17]
```diff
@@ -104,20 +107,10 @@ def index
   end
 
   def create
-    new_competition_params = params.require(:competition).permit(:name, :competition_id_to_clone)
-    @competition = Competition.new(new_competition_params.merge(
-                                   registration_open: 1.week.from_now,
-                                   registration_close: 2.weeks.from_now))
```
Comment (jonatanklosko) [inline WcaOnRails/app/controllers/competitions_controller.rb]: Why have you removed the registration dates from here? Maybe we can handle this in the model with
```ruby
after_initialize :set_default_registration_dates
private def set_default_registration_dates
  registration_open ||= # default
  registration_close ||= # default
```
@larspetrus @jfly do you see any cleaner way?

Comment (larspetrus) [inline WcaOnRails/app/controllers/competitions_controller.rb]: Depends on why we are/were assigning arbitrary values to these fields.

Without knowing the goal it's hard to say what the best way to reach it is.

Comment (jonatanklosko) [inline WcaOnRails/app/controllers/competitions_controller.rb]: Oh, actually it doesn't seem to be necessary. I just assumed there was a reason for that. Nevermind!

**Comment by pingskills** [comment]
Cleaned up `build_clone` as suggested by @jonatanklosko and added new test as suggested by @larspetrus. I also removed the confirm button from the new page.

File: WcaOnRails/app/models/competition.rb [hunk 18]
```diff
@@ -100,16 +102,10 @@ def info
...
-    attributes_to_clone = attributes
-    %w(id name cellName year month day endMonth endDay registration_open registration_close results_posted_at).each { |attribute| attributes_to_clone.delete attribute }
-    clone = Competition.new
-    clone.assign_attributes(attributes_to_clone)
-    clone.organizers = organizers
-    clone.delegates = delegates
-    clone.showAtAll = false
-    clone.isConfirmed = false
-    clone
+    Competition.new(attributes.except(*UNCLONEABLE_ATTRIBUTES)).tap do |clone|
```
Comment (jonatanklosko) [inline WcaOnRails/app/models/competition.rb]: As you've added both attributes groups as Lars suggested, it would be better to do `attributes.slice(CLONABLE_ATTRIBUTES)` here.

This really cleaned things up.

File: WcaOnRails/spec/models/competition_spec.rb [hunk 19]
```diff
@@ -206,6 +206,10 @@
     expect(competition.longitude).to eq 4.6*1e6
   end
 
+  it "ensures all attributes are defined as either cloneable or uncloneable" do
+    expect(Competition.column_names()).to match_array(Competition::CLONEABLE_ATTRIBUTES + Competition::UNCLONEABLE_ATTRIBUTES)
```
Comment (jonatanklosko) [inline WcaOnRails/spec/models/competition_spec.rb]: Please remove this empty `()` =)

File: WcaOnRails/app/models/competition.rb [hunk 20]
```diff
@@ -96,24 +101,10 @@ def info
...
-        attributes["showAtAll"] = false
-        attributes["isConfirmed"] = false
-        assign_attributes(attributes)
-        self.organizers |= competition_to_clone.organizers
-        self.delegates |= competition_to_clone.delegates
-      else
-        errors.add(:competition_id_to_clone, "invalid")
-      end
+  def build_clone
+    Competition.new(attributes.except(*UNCLONEABLE_ATTRIBUTES)).tap do |clone|
```
Comment (jonatanklosko) [inline WcaOnRails/app/models/competition.rb]: As you've added both attributes groups as Lars suggested, it would be better to do
```ruby
attributes.slice(CLONABLE_ATTRIBUTES)
```

This really cleaned things up.

File: WcaOnRails/app/controllers/competitions_controller.rb [hunk 21]
```diff
@@ -239,16 +232,25 @@ def edit
...
+    if current_user.any_kind_of_delegate?
+      @competition.delegates |= [current_user]
+    end
+    render :new
+  end
+
   def nearby_competitions
-    @competition = Competition.find(params[:id])
+    @competition = Competition.new
     @competition.assign_attributes(competition_params)
```
Comment (jonatanklosko) [inline WcaOnRails/app/controllers/competitions_controller.rb]:
```ruby
@competition = Competition.new(competition_params)
```

**Comment by pingskills** [comment]
Updated to use CLONEABLE_ATTRIBUTES in build_clone method

File: WcaOnRails/app/controllers/competitions_controller.rb [hunk 22]
```diff
@@ -239,16 +232,25 @@ def edit
...
     @competition.valid? # We only unpack dates _just before_ validation, so we need to call validation here
     @competition_admin_view = params.key?(:competition_admin_view) && current_user.can_admin_results?
     render partial: 'nearby_competitions'
   end
 
   def time_until_competition
-    @competition = Competition.find(params[:id])
+    @competition = Competition.new
     @competition.assign_attributes(competition_params)
```
Comment (jonatanklosko) [inline WcaOnRails/app/controllers/competitions_controller.rb]:
```ruby
@competition = Competition.new(competition_params)
```

File: WcaOnRails/app/models/competition.rb (hunk 13 above)
Comment (jonatanklosko) [inline WcaOnRails/app/models/competition.rb]: Despite of the fact that `&&` is stronger, I feel like parentheses should go here for explicitness. If you think that's personal feeling and you don't think the same, just ignore this comment =)

**Comment by jonatanklosko** [comment]
Ok, last two comments for you and that LGTM!

File: WcaOnRails/app/models/competition.rb (hunk 13 above)
Comment (pingskills) [inline WcaOnRails/app/models/competition.rb]: That makes sense to me @jonatanklosko. I've added the parentheses.

**Comment by pingskills** [comment]
OK. I've made those changes :)

File: WcaOnRails/app/controllers/competitions_controller.rb (hunk 17 above)
Comment (jfly) [inline WcaOnRails/app/controllers/competitions_controller.rb]: I think this was added in 75de58d46e3c474f260a4c83cdbb7afcf3beda3f because `registration_open` and `registration_close` were both `NOT NULL`.

Later on (17506dd8131cb30c6a3c9bc9925f8755cee84eab), it looks like we changed these fields to be nullable, but didn't change this code to no longer set `registration_open` and `registration_close`. I support removing these defaults now.

File: WcaOnRails/app/models/competition.rb [hunk 23]
```diff
@@ -15,18 +15,23 @@ class Competition < ActiveRecord::Base
   has_many :organizers, through: :competition_organizers
   has_many :media, class_name: "CompetitionMedium", foreign_key: "competitionId", dependent: :delete_all
 
+  CLONEABLE_ATTRIBUTES = %w(cityName countryId information eventSpecs venue venueAddress venueDetails website latitude longitude contact remarks use_wca_registration guests_enabled).freeze
+  UNCLONEABLE_ATTRIBUTES = %w(id name year month day endMonth endDay cellName showAtAll isConfirmed registration_open registration_close results_posted_at).freeze
```
Comment (jfly) [inline WcaOnRails/app/models/competition.rb]: This looks really awesome now, Jeff!

Could you split these 2 lines into one line per attribute? That means that future diffs will be easier to read, and the chances of conflicts are smaller. As we work on #329, I suspect that Competitions will continue to gather more and more attributes.

**Comment by jfly** [comment]
One comment from me about splitting the `CLONEABLE_ATTRIBUTES` and `UNCLONEABLE_ATTRIBUTES` into multiple lines, but otherwise LGTM!

File: WcaOnRails/app/models/competition.rb (hunk 23 above)
Comment (pingskills) [inline WcaOnRails/app/models/competition.rb]: Sure that makes a lot of sense. I'll split those lines out.

**Comment by pingskills** [comment]
I separated out CLONEABLE_ATTRIBUTES and UNCLONEABLE_ATTRIBUTES onto a separate line for each attribute. I wasn't really sure the best way to format that so let me know if you think it's OK how I did it. Thanks.

File: WcaOnRails/app/models/competition.rb [hunk 24]
```diff
@@ -15,18 +15,48 @@ class Competition < ActiveRecord::Base
...
+                            venue
+                            venueAddress
+                            venueDetails
+                            website
+                            latitude
+                            longitude
+                            contact
+                            remarks
+                            use_wca_registration
+                            guests_enabled).freeze
```
Comment (jfly) [inline WcaOnRails/app/models/competition.rb]: This looks great! I might have done this to reduce indentation and not make the first/last ones special:

```ruby
CLONEABLE_ATTRIBUTES = %w(
  cityName
  countryId
  information
  eventSpecs
  venue
  venueAddress
  venueDetails
  website
  latitude
  longitude
  contact
  remarks
  use_wca_registration
  guests_enabled
).freeze
```

**Comment by jfly** [comment]
LGTM! :ship: :shipit:

File: WcaOnRails/app/models/competition.rb (hunk 24 above)
Comment (jonatanklosko) [inline WcaOnRails/app/models/competition.rb]: What about grouping related fields? This would save some space, but I'm not sure what's better =)
```ruby
CLONEABLE_ATTRIBUTES = %w(
  countryId cityName
  venue venueAddress venueDetails
  contact website information remarks
  eventSpecs
  latitude longitude
  use_wca_registration
  guests_enabled
).freeze
UNCLONEABLE_ATTRIBUTES = %w(
  id name cellName
  year month day
  endMonth endDay
  showAtAll isConfirmed
  registration_open registration_close
  results_posted_at
).freeze

```
