### PR TITLE
Competitions index fix

### LINKED ISSUE #499: Competitions#index empty without JS enabled
screen shot 2016-04-15 at 10 37 44 am

Is this intentional? Why is the content hidden by default?

### PR DESCRIPTION
**Pull request by jonatanklosko**
Fixes #499.

### CODE REVIEW

File: WcaOnRails/app/controllers/competitions_controller.rb [hunk 1]
```diff
@@ -18,7 +18,23 @@ def new
...
 
+  # Normalizes the params that old links to index still work.
+  private def support_old_links
+    params[:display].downcase! if params[:display]  # 'List' -> 'list', 'Map' -> 'map'
+
+    if params[:years] == "all"
+      params[:state] = "past"
+      params[:year] = "all years"
+    elsif params[:years].to_i >= Date.today.year  #to_i: 'If there is not a valid number at the start of str, 0 is returned.' - RubyDoc
+        params[:state] = "past"
```
Comment (jfly) [inline WcaOnRails/app/controllers/competitions_controller.rb]: Nit: indentation?

File: WcaOnRails/app/controllers/competitions_controller.rb [hunk 2]
```diff
@@ -18,7 +18,23 @@ def new
...
+        params[:year] = params[:years]
+    end
+    params[:years] = nil
+  end
+
   def index
+    support_old_links
```
Comment (jfly) [inline WcaOnRails/app/controllers/competitions_controller.rb]: Ruby style question: Would it make sense to put a ! at the end of this method definition, as it has a side effect?

File: WcaOnRails/app/assets/stylesheets/competitions.scss [hunk 3]
```diff
@@ -169,7 +169,11 @@ $venue-map-wrapper-height: 400px;
 
   #state {
     min-width: 220px;
-    width: 100%;
+    display: block;
+    @media (max-width: $screen-sm) {
```
Comment (jfly) [inline WcaOnRails/app/assets/stylesheets/competitions.scss]: This looks like something special for mobile, can you include a screenshot on a tiny and large screen?

**Comment by jfly** [comment]
LGTM!
