### PR TITLE
Fix export registrations

### LINKED ISSUE #540: Automated e-mail modification
For North London Open 2016, we had a ridiculously large waiting list of 50 people and we have had to turn them away. However, to import to CubeComps we needed to delete all those on the waiting list.

We sent out a mass e-mail explaining the situation to the waiting list and how they wouldn't get a spot, and then we have to delete the registrations. However people were not too pleased with the automated deletion emails and we got lots of responses for that asking about the situation.

One way to solve this would be to allow the automated message to be customised, allowing us to explain the situation to everyone and deleting them at the same time without actually having to send out an email. Another option would be to just allow us to turn off the automated email.

I can't think of any other ways to handle this right now, but I think it should be discussed a bit, which was the main point of the issue.

### PR DESCRIPTION
**Pull request by jonatanklosko**
Fixes #540. Now an authorized user can select which registrations should be exported to CSV.

### CODE REVIEW

File: WcaOnRails/app/controllers/registrations_controller.rb [hunk 1]
```diff
@@ -104,13 +96,28 @@ def destroy
...
+
+    respond_to do |format|
+      format.csv do
+        headers['Content-Disposition'] = "attachment; filename=\"#{@competition.id}-registration.csv\""
+        headers['Content-Type'] ||= 'text/csv; charset=UTF-8'
+      end
     end
+  end
+
+  def do_actions_for_slected
```
Comment (jfly) [inline WcaOnRails/app/controllers/registrations_controller.rb]: `do_actions_for_slected` -> `do_actions_for_selected` =)

File: WcaOnRails/app/controllers/registrations_controller.rb [hunk 2]
```diff
@@ -134,12 +141,17 @@ def update_all
...
       flash.now[:warning] = "#{"Registration".pluralize(registrations.length)} deleted"
+    when "export-selected"
     else
       raise "Unrecognized action #{params[:registrations_action]}"
     end
 
     respond_to do |format|
-      format.js { }
+      if params[:registrations_action] == "export-selected"
+        format.js { render "redirect_to_export" }
```
Comment (jfly) [inline WcaOnRails/app/controllers/registrations_controller.rb]: nitpick: I feel like most of our calls to render actually use a symbol rather than a string.

**Comment by jfly** [comment]
One minor typo, but otherwise looks good to me!

**Comment by jonatanklosko** [comment]
I fixed the mentioned things and removed the empty partial which I've just noticed.

**Comment by jfly** [comment]
LGTM!
