### PR TITLE
Instant feedback on wrong birthdate.

### LINKED ISSUE #369: Show the user that birthdate is inputted wrong.
We added the model validation, but I'd like to give some instant feedback so hopefully they can fix it before clicking submit.

See here for an example: http://jsfiddle.net/0Ltv25o8/2355/

### PR DESCRIPTION
**Pull request by pedrosino**
Fixes #369

### CODE REVIEW

**Comment by jfly** [comment]
Good point, @pedrosino. It looks like pickers.js was added in https://github.com/cubing/worldcubeassociation.org/commit/30a26ebcc2f1aec64dc3910f6495c0b98c9ae693, and you can see that we also added it to application.js.

How about deleting pickers.js vendor file and removing the corresponding require from applicaiton.js?

File: WcaOnRails/app/inputs/date_picker_input.rb [hunk 1]
```diff
@@ -3,10 +3,10 @@ def input(wrapper_options)
     set_html_options
     set_value_html_option
 
-    template.content_tag :div, class: 'input-group date datetimepicker' do
+    #template.content_tag :div, class: 'input-group date datetimepicker' do
       input = super(wrapper_options) # leave StringInput do the real rendering
-      input_button + input + utc_addon
-    end
+    #  input_button + input + utc_addon
```
Comment (jfly) [inline WcaOnRails/app/inputs/date_picker_input.rb]: Commented out code =(. How are users going to know that times are in UTC? Can we leave the UTC addon, or make it obvious some other way?

File: WcaOnRails/app/views/users/edit.html.erb [hunk 2]
```diff
@@ -159,3 +159,17 @@
     <%= f.submit 'Save', class: "btn btn-primary" %>
   <% end %>
 </div>
+
+<script>
+$('.date_picker.form-control').on('dp.error', function(e){
```
Comment (jfly) [inline WcaOnRails/app/views/users/edit.html.erb]: I'm happy to see you went with something less obstrusive than an `alert` =)

Do we only want this on the users edit page, not everywhere?

I haven't checked out exactly what this does, but did you consider using bootstrap's validation states? I feel like that might be all you need here. See <http://getbootstrap.com/css/#forms-control-validation>

Comment (pedrosino) [inline WcaOnRails/app/views/users/edit.html.erb]: This is the only place where they input a birthdate and we save, so I guess it's fine.

Unless you mean everywhere as in every input in every page. In that case, that's a LOT of work which is probably not worth at this point.

I was using the .has-error, but the calendar also turned red, which didn't make much sense.

File: WcaOnRails/app/inputs/date_picker_input.rb (hunk 1 above)
Comment (pedrosino) [inline WcaOnRails/app/inputs/date_picker_input.rb]: I forgot to actually delete the commented part. Actually I was waiting to see what you'd say about the thing (like the UTC part) :)

Let's try adding the utc_addon back...

**Comment by pedrosino** [comment]
Will do it. Let's see if things still work.

File: WcaOnRails/app/inputs/date_picker_input.rb (hunk 1 above)
Comment (pedrosino) [inline WcaOnRails/app/inputs/date_picker_input.rb]: Because we no longer have a div wrapping the input, the UTC thing is the same width as the page. Also the datepicker doesn't work :P
(The input-with-no-button doesn't work if you wrap it with something, so...)
utc

There is a note saying times are in UTC just below...
Do we use this somewhere else other than registration open/close?
utc2

I'm commiting a "solution": adding a similiar note to the registration open/close fields.

Comment (pedrosino) [inline WcaOnRails/app/inputs/date_picker_input.rb]: EDIT
I got it working with the UTC addon in the right place (the rendered input is a datetime_picker here, not a date_picker as I set in application.js...just added a couple lines there to make both work).

I still like the note about the registrations, if only for consistency. (or remove the one in polls/edit)

File: WcaOnRails/app/views/users/edit.html.erb (hunk 2 above)
Comment (jfly) [inline WcaOnRails/app/views/users/edit.html.erb]: Oh, I meant every date and datetime input on every page, not every single input everywhere. Presumably people will try typing in poorly formatted dates elsewhere...

File: WcaOnRails/app/inputs/date_picker_input.rb (hunk 1 above)
Comment (jfly) [inline WcaOnRails/app/inputs/date_picker_input.rb]: I agree, the note about UTC is nice. I also like the consistency. It would
be neat if we could automatically add the note about UTC...

**Comment by jfly** [comment]
If this still works, it looks good to me! Let me know, and I'll merge it up!

File: WcaOnRails/app/views/users/edit.html.erb (hunk 2 above)
Comment (pedrosino) [inline WcaOnRails/app/views/users/edit.html.erb]: I guess that's possible if we move the javascript to application.js, right?

**Comment by pedrosino** [comment]
Moved everything to application.js and still works here :) I think we're good to go, once Travis is happy.
